function all_stats = generate_mod_index_plots(context_mod_all, celltypes_ids, params, save_dir)
    % Generate all modulation index plots

    %save all stats
    all_stats = {};
    
    % Heatmap
    mod_index_heatmap(save_dir, context_mod_all, params.plot_info, ...
        params.info.chosen_mice, params.plot_info.y_lims);
    
    % CDF Plot % Options: 'all' for all cells, 'celltype' to separate by cell type.
    [all_stats.cdf_stats, KW_Test] = cdf_mod_index_across_contexts(save_dir, ...
        context_mod_all, [], params.plot_info.behavioral_contexts, ...
        params.plot_info.colors_celltypes_2contexts, ...
        params.plot_info.lineStyles_contexts, params.info.chosen_mice, ...
        params.plot_info.plot_labels, celltypes_ids, 'celltype', ...
        params.plot_info.y_lims);
    
    % Violin and Box plots
    [all_stats.box_stats] = mod_index_violin_across_celltypes(save_dir, ...
        context_mod_all, params.plot_info.behavioral_contexts, ...
        params.plot_info.colors_celltypes, 2, celltypes_ids, ...
        params.info.chosen_mice, params.plot_info.y_lims*2);
    
    % Scatter Plot of abs(mod index)
    [all_stats.abs_mod_stats_celltypes] = scatter_abs_mean_mod(save_dir, ...
        context_mod_all, params.plot_info, celltypes_ids, ...
        params.info.chosen_mice, 2, [0,params.plot_info.y_lims(2)/2]);
end