[all_celltypes, dff_st, deconv_st, stim_info, ...
 mouse_context_tr, deconv_st_interp, alignment_frames] = ...
    pool_activity_more_events(params.info.mouse_date, params.info.serverid, params.info.path_string, true, [60,30]);
